import java.io.Serializable;

/**
 * @author Fareen. L
 * @version 10.25.2020
 */
public enum CountryName implements Serializable {
    Alaska,
    WesternCanada,
    CentralAmerica,
    EasternUS,
    Greenland,
    NorthwestTerritories,
    CentralCanada,
    EasternCanada,
    WesternUS,
    Argentina,
    Brazil,
    Peru,
    Venezuela,
    GreatBritain,
    Iceland,
    NorthernEurope,
    Scandinavia,
    SouthernEurope,
    Ukraine,
    WesternEurope,
    Congo,
    EastAfrica,
    Egypt,
    Madagascar,
    NorthAfrica,
    SouthAfrica,
    Afghanistan,
    China,
    India,
    Irkutsk,
    Japan,
    Kamchatka,
    MiddleEast,
    Mongolia,
    Siam,
    Siberia,
    Ural,
    Yakutsk,
    EasternAustralia,
    Indonesia,
    NewGuinea,
    WesternAustralia,
}